version: '1.9'
services:
  postgresql:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=pasword
      - POSTGRES_USER=alliano-dev
    volumes:
      - pg_volume:/var/lib/postgresql/data
volumes:
 pg_volume: {}
