server:
  port: 8091
spring:
  profiles:
    active:
    - dev
  application:
    name: spring-security
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security
    username: ${psql_username}
    password: ${psql_password}
    hikari:
      connection-timeout: 60000
      idle-timeout: 600000
      max-lifetime: 18000
      maximum-pool-size: 20
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialec: org.hibernate.dialect.PostgreSQLDialect
        '[format_sql]': true
logging:
  level:
    org:
      springframework:
        security:
          web:
            FileterChainProxy: DEBUG